lojaintegrada/admin-components

styleguide/cypress/plugins/index.ts
styleguide/package.json
styleguide/src/Components/Button/Button.spec.tsx
styleguide/src/Components/Timeline/Timeline.spec.tsx
styleguide/src/Forms/Input/Input.spec.tsx
styleguide/src/Forms/InputHelpText/InputHelpText.spec.tsx
styleguide/src/Forms/InputHelpText/InputHelpText.tsx
styleguide/src/Forms/InputLabel/InputLabel.spec.tsx
styleguide/src/Forms/InputLabel/InputLabel.tsx
styleguide/src/Forms/Select/Select.spec.tsx
styleguide/src/Icons/Icon.spec.tsx
styleguide/src/Icons/Icon.tsx
styleguide/src/Indicators/Status/Status.spec.tsx
styleguide/src/Indicators/Status/Status.tsx
styleguide/src/Indicators/Toast/Toast.spec.tsx
styleguide/src/Navigation/Breadcrumb/Breadcrumb.spec.tsx
styleguide/src/Navigation/Breadcrumb/Breadcrumb.stories.tsx
styleguide/src/Navigation/Breadcrumb/index.tsx
styleguide/src/Navigation/Pagination/Pagination.spec.tsx
styleguide/src/Navigation/Pagination/Pagination.stories.tsx
styleguide/src/Navigation/Pagination/PaginationInfo.tsx
styleguide/src/Navigation/Pagination/PaginationNav.tsx
styleguide/src/Navigation/Pagination/index.tsx

https://app.clickup.com/t/5t7p9f
Missing tests to:
- Box
- Sidebar
- Topbar
- Table
- LoadingPlaceholder
Reason: This components don't have a stable version yet.

Add tests to: button, timeline, input, select, icon, status, toast, breadcrumb, pagination

---

.github/workflows/publish-styleguide.yml

Try new publish flow

---

styleguide/.storybook/preview.js
styleguide/package.json
styleguide/src/Components/Timeline/Timeline.tsx
styleguide/src/Components/Timeline/TimelineItem.tsx
styleguide/src/Forms/Input/Input.tsx
styleguide/src/Forms/InputCurrency/InputCurrency.spec.tsx
styleguide/src/Forms/InputCurrency/InputCurrency.stories.tsx
styleguide/src/Forms/InputCurrency/InputCurrency.tsx
styleguide/src/Forms/InputCurrency/index.ts
styleguide/src/Forms/InputCurrency/utils.ts
styleguide/src/Forms/InputMask/InputMask.spec.tsx
styleguide/src/Forms/InputMask/InputMask.stories.tsx
styleguide/src/Forms/InputMask/InputMask.tsx
styleguide/src/Forms/InputMask/index.ts
styleguide/src/Forms/InputMask/maskDate.ts
styleguide/src/Forms/InputMask/utils.ts
styleguide/src/Forms/index.ts
styleguide/src/utils/index.ts
styleguide/yarn.lock

https://app.clickup.com/t/65bquv
Novos componentes criados:
`InputMask`
`InputCurrency`
Chromatic

Input Mask

---

styleguide/src/Layout/Box/Box.spec.tsx
styleguide/src/Layout/Box/Components/Separator/BoxSeparator.tsx
styleguide/src/Layout/Box/Components/utils.ts

Fix top/bottom padding of box content

---

styleguide/src/Layout/Box/Components/Header/BoxHeader.tsx

Update header font size

---

styleguide/src/Components/Table/Table.stories.tsx
styleguide/src/Components/Table/Table.tsx

https://app.clickup.com/t/63b18u
Table should have an empty state.
The content can be a string or a react component.

Add empty state to table

---

styleguide/src/Indicators/Alert/Alert.spec.tsx
styleguide/src/Indicators/Alert/Alert.stories.tsx
styleguide/src/Indicators/Alert/Alert.tsx
styleguide/src/Indicators/Alert/index.tsx
styleguide/src/Indicators/index.ts

https://app.clickup.com/t/8taefx
Adicionado novo componente de Alert.
Adicionado apenas as funções básicas, necessario implementar depois:
- Botão de fechar
- Alerta com icone

New component: Alert

---

styleguide/src/Indicators/Badge/Badge.spec.tsx
styleguide/src/Indicators/Badge/Badge.stories.tsx
styleguide/src/Indicators/Badge/Badge.tsx
styleguide/src/Indicators/Badge/index.tsx
styleguide/src/Indicators/index.ts

https://app.clickup.com/t/1fck6dv
Criação do componente de badge.
Componente faltando.
Comparando com o [Figma](https://www.figma.com/file/Z2WDD4SH8zwaJC2K5wbtMO/Sistema-Integrado?node-id=98%3A7360).

New component: Badge

---

styleguide/src/Forms/Toggle/Toggle.tsx

Correções no componente de toggle, para deixar igual as alterações feitas no design system.
- Label do toggle não vai receber mais o semibold quando o toggle tiver ativo;
- Removido opacidade quando toggle estiver `disabled`;
- Ajuste no espaço horizontal do círculo do toggle.
https://www.figma.com/file/Z2WDD4SH8zwaJC2K5wbtMO/Sistema-Integrado?node-id=95%3A6365

Some fixes in toggle component

---

styleguide/src/Components/ActionBar/ActionBar.spec.tsx
styleguide/src/Components/ActionBar/ActionBar.stories.tsx
styleguide/src/Components/ActionBar/ActionBar.tsx
styleguide/src/Components/ActionBar/index.tsx
styleguide/src/Components/index.ts

https://app.clickup.com/t/1pch251
O intuito desse componente é fornecer uma forma padronizada para agrupar todos os botões de ação na interface que ele está inserido, tanto no Web quanto Mobile.
Adicionando um ou mais botões dentro do componente e verificar o comportamento. No Web não pode haver ícones, já em interfaces que só vão possuir ações no Mobile, é possível utilizar a propriedade: onlyMobile.

New component: ActionBar

---

styleguide/package.json
tailwindcss/package.json

feat: changing scope of apps

---

.github/workflows/publish-tailwindcss.yml

update tailwindcss publish public

---

styleguide/src/Components/Button/Button.tsx

https://app.clickup.com/t/1rbawfb
Adicionando variant outline que não tinha sido feita de acordo com o figma do Sistema integrado
https://www.figma.com/file/Z2WDD4SH8zwaJC2K5wbtMO/Sistema-Integrado?node-id=84%3A4800
Testar comportamentos previstos no figma

Feat/ outline button variant

---

styleguide/src/Components/Modal/Modal.tsx

Ajustando tamanho da modal tipo `small`

fix: modal small size

---

styleguide/src/Components/Modal/Modal.tsx
styleguide/src/Components/Table/Table.stories.tsx
styleguide/src/Components/Table/Table.tsx

https://app.clickup.com/t/1tkcyjt
Adicionando id ao botão de fechar da modal e aos checkbox da tabela.

fix: add ids to button close modal and table checkboxes

---

styleguide/src/Forms/Dropdown/Dropdown.tsx
styleguide/src/Forms/InputMask/utils.ts
styleguide/src/Forms/Toggle/Toggle.tsx
styleguide/src/Indicators/Tooltip/Tooltip.stories.tsx
styleguide/src/Indicators/Tooltip/Tooltip.tsx

Ajustes em componentes.
- Ajustando cor do valor selecionado no Dropdown
- Ajustando máscara onlyText para permitir trema e considerar til enquanto digita
- Ajustando estilo do toggle para o [mesmo do sistema integrado](https://www.figma.com/file/Z2WDD4SH8zwaJC2K5wbtMO/Sistema-Integrado?node-id=95%3A6365)
- Adicionando nova prop `theme` na tooltip, e ajustando cor de fundo padrão 
https://60d36f60766f7d0045e93767-pupxumoswf.chromatic.com/

Adjusts in dropdown, toggle, inputMask and tooltip

---

styleguide/src/Navigation/Pagination/PaginationNav.tsx

Adiciona `type="button"` nos botões do componente de paginação.
Usando dentro de um form, ao clicar nos botões de paginação ocorria o evento, não pretendido, de submit.

fix: add button type to pagination buttons

---

tailwindcss/README.md
tailwindcss/package.json
tailwindcss/src/defaultPreset.js
tailwindcss/yarn.lock

Instruções para migrar/atualizar seu projeto:
https://tailwindcss.com/docs/upgrade-guide
- Upgrade tailwindcss to v3
- Para usar as novas features do tailwind, é necessário migra-lo para a nova versão
- Não possui mudanças visuais, apens deve continuar funcionando

Upgrade tailwindcss to v3

---

styleguide/src/Components/Modal/Modal.tsx

Add prop `closeTimeout`.
The prop `closeTimeoutMS` today is hardcoded.

feat: add prop close timeout to modal

---

tailwindcss/package.json
tailwindcss/plugins/paddingSafe.js
tailwindcss/src/defaultPreset.js
tailwindcss/yarn.lock

- Remove a dependencia e trás código do plugin para dentro do repo

Remove padding safe plugin and bring him inside

---

tailwindcss/src/defaultPreset.js

Foi solicitado a alteração das cores com hexadecimal #607081 para o #525B65.

Change the gray of colors

---

styleguide/src/Indicators/Tooltip/Tooltip.tsx

Adiciona verificação da variavel global window
Possibilita o uso do componente Tooltip em SSR sem obter erro 
Faça o uso do tooltip em SSR

:sparkles: adiciona verificação de variável window no componente Tooltip

---

styleguide/src/Navigation/Breadcrumb/index.tsx

Adiciona correção no componente breadcrumb
Corrige alinhamento de textos
Visualização do componente

:bug: corrige corta de textos no componente breadcrumb

---

styleguide/package.json
styleguide/yarn.lock

Bumping tailwindcss-config version on styleguide
Newly added color palette not being recognized on styleguide

bumps tailwindcss-config version on styleguide

---

styleguide/src/Forms/Dropdown/Dropdown.tsx
styleguide/src/Forms/FloatingLabelInput/FloatingLabelInput.stories.tsx
styleguide/src/Forms/FloatingLabelInput/FloatingLabelInput.tsx

Melhorar visibilidade dos components floating e variant do simple do dropdown no mobile
adiciona bordas indicando que o input está ali e aberto

fix: border on dropdown and floating input for mobile visibility

---

styleguide/package.json
styleguide/yarn.lock

chore: bump tailwindcss-config

---

styleguide/src/Indicators/Tooltip/style.scss
styleguide/src/tailwind.css
styleguide/tsdx.config.js

fix: inject style of component instead extract in unique file

---

styleguide/package.json
tailwindcss/package.json

chore: add package repo url

---

.github/WORKFLOW_sonar.yml
.github/workflows/chromatic.yml
.github/workflows/main.yml
.github/workflows/monrepo.yaml
.github/workflows/publish-styleguide.yml
.github/workflows/publish-tailwindcss.yml

ubuntu to self-hosted

---

styleguide/src/Components/Tabs/TabsItem.tsx

fix: add type button to prevent submit form

---

styleguide/src/Indicators/InformationBox/InformationBox.spec.tsx
styleguide/src/Indicators/InformationBox/InformationBox.tsx

Inserir 2 novos atributos (showClose e onClose) para renderizar um botão "Fechar" e fornecer um Callback quando ocorrer a ação.

Add button to close the InformationBox

---

styleguide/src/Icons/icons-path/Table.tsx
styleguide/src/Icons/icons-path/index.ts

Adicionar ícone do Design System ausente
Adicionar ícone `table`
Sim

Add icon Table

---

.github/CODEOWNERS

Removendo o time de QA da lista de owners pois não é necessário no nosso processo.
Acionamento desnecessário.

remove owner qateam
