tailwindcss/src/defaultPreset.js
Adiciona 2 novas cores ao preset do Tailwind:
- focus: `#5690F7`
- black: `#000000`
Cores faltando.
=> feat: add black and focus colors in tailwind

.github/workflows/monrepo.yaml, styleguide/src/Components/Modal/Modal.tsx
- Botão salvar nem sempre aparecia no iOs/safari quando conteúdo do modal era muito grande, devido a forma com que o safari lida com o 100vh
- No iOs/safari ao dar scroll no conteúdo do modal, também acionava o scroll na página inteira atrás
- Quando conteúdo do modal é muito grande e precisava de scroll, o scroll aparecia no meio do modal, depois do padding interno. Alterado para aparecer no canto extremo
=> Fix wrong behaviour on mobile at safari mobile

styleguide/src/Forms/Input/Input.spec.tsx, styleguide/src/Forms/Input/Input.stories.tsx, styleguide/src/Forms/Input/Input.tsx, styleguide/src/Forms/InputCurrency/InputCurrency.stories.tsx, styleguide/src/Forms/InputMask/InputMask.stories.tsx, styleguide/src/Forms/InputMask/InputMask.tsx, styleguide/src/Forms/Select/Select.tsx, styleguide/src/Forms/commonStyles.ts
Adicionar as props opcionais para poder adicionar um elemento de sufixo ou prefixo num campo de texto.
Resolve o problema que os inputs atuais não possuíam essa opção, por exemplo : input de dinheiro não tinha o cifrão na frente com sufixo
pode ser testado adicionando a propriedade `startAdornment` ou `endAdornment` a um input, tanto string quanto um html/icone
já deixei alguns exemplos na maiorias dos inputs
=> feat: add start/end input adornments

styleguide/src/Components/Modal/Modal.tsx
Adicionando prop para impedir fechamento da modal.
No onboarding do Manda LI, a partir da 2a etapa, a modal não exibe o botão de fechar e não é possível fechá-la usando `ESC` ou clicando fora (no overlay).
Pressionar ESC ou clicar fora da modal não fecham a modal e botão de x não deve ser exibido.
=> feat: prevent close modal

styleguide/src/Forms/Checkbox/Checkbox.spec.tsx, styleguide/src/Forms/Checkbox/Checkbox.stories.tsx, styleguide/src/Forms/Checkbox/Checkbox.tsx
Permitir conteúdo html dentro da label do checkbox, e ajeitar algumas classes.
Label só aceitava string e precisamos de um `<a>` pra checkbox de termos de uso.
[Figma](https://www.figma.com/file/Z2WDD4SH8zwaJC2K5wbtMO/Sistema-Integrado?node-id=95%3A6365)
=> fix: class refinement and checkbox label allow node

styleguide/src/Forms/commonStyles.ts
Sufix e PRefix estavam sem a margem top negativa, fazendo assim com que ele ficasse com uma altura maior que a div parent, causando problemas de posicionamento no layout.
Suffix e Prefix com a mesma altura do seu respectivo container
=> Suffix should have same height as parent

styleguide/src/Forms/Dropdown/Dropdown.stories.tsx, styleguide/src/Forms/Dropdown/Dropdown.tsx, styleguide/src/Forms/Toggle/Toggle.tsx
Adicionar as props de onBlur, defaultValue e maxMenuHeight
resolve o problema de não conseguir capturar o evento de onBlur para validações por exemplo e não poder setar um valor inicial para o dropdown, também o maxMenuHeight para poder personalizar o tamanho dos menus  com as opções do dropdown
=> feat: onblur and default value for dropdown

styleguide/src/Indicators/Alert/Alert.tsx
Alert subtitle accept reactNode and actions don't shrink
- Allow send `<div>` inside `subtitle`
- Action buttons don't break inner text
Before:
After:
=> Alert subtitle accept reactNode and actions don't shrink

styleguide/src/Forms/Toggle/Toggle.tsx, styleguide/src/Layout/Box/Components/Content/BoxContent.tsx
Algumas correções simples.
Toggle usando flex é possível clicar fora dele (na mesma linha) e ativar/desativar, inline-flex previne isso;
isOpen estava gerando classe `false`
=> fix: toogle inline flex and box content class

styleguide/src/Layout/ActionBar/ActionBar.stories.tsx, styleguide/src/Layout/ActionBar/ActionBar.tsx
Adicionando uma checagem para verificar se a children é válida e tem conteudo
Ao passar um fragment vazio a action bar entendia como uma children válida e deixava um botão vazio renderizado
=> Fix/ empty children on action bar

styleguide/src/Forms/Checkbox/Checkbox.tsx
Add the `boxAlign` option to choose the alignment of the checkbox input (center or baseline).
The checkox input is always align to the center, but I have the situation when there is a span with multiple lines and I need to align the input with the first span line.
When there is a span with just one line, the baseline and center should have the same effect.
When there is a span with more than one line, the baseline option should align the input box with the first line, and the center option should aslign with center.
Multiple lines:
Single line:
Multiple lines:
Single line:
=> feat: add checkbox option to align the input box

styleguide/src/Components/Button/Button.spec.tsx, styleguide/src/Components/Button/Button.tsx
Add button variant to be used into forms.
This button variant already exists into design systems, but just with forms, it did not exist as component button.
Just use the outlineSecondary as button variant.
Normal:
Hover:
Active:
Focus:
=> feat: add outlineSecondary button variant

styleguide/src/Components/Button/Button.tsx, styleguide/src/Layout/ActionBar/ActionBar.tsx
- Valor padrão `type` do `<Button>` ser `button`
- Caso nenhum type seja enviado, o browser considera como `submit`, podendo causar cenários não esperados
=> Set default type for button

styleguide/src/Indicators/Badge/Badge.spec.tsx, styleguide/src/Indicators/Badge/Badge.stories.tsx, styleguide/src/Indicators/Badge/Badge.tsx
Adiciona prop `expanded` para permitir width adaptativo para o componente `badge`.
Badge tinha um tamanho fixado no conteúdo, não permitindo sua expansão, para usar como na imagem abaixo:
https://60d36f60766f7d0045e93767-pftepdbhup.chromatic.com/?path=/story/indicators-badge--expanded
=> feat: add prop expanded in badge component

styleguide/src/Components/Timeline/Timeline.spec.tsx, styleguide/src/Components/Timeline/Timeline.stories.tsx, styleguide/src/Components/Timeline/Timeline.tsx, styleguide/src/Components/Timeline/TimelineItem.interface.ts, styleguide/src/Components/Timeline/TimelineItem.tsx
Adiciona prop `toggleItems` no componente `Timeline` para gerenciar exibição do toggle em um item de timeline.
É possível definir individualmente o estado da exibição do toggle em um item.
Adiciona também ícone do relógio ao lado do timestamp.
No Enviali deixaremos visível a descrição de um item, sem toggle.
https://60d36f60766f7d0045e93767-tnyhufzopz.chromatic.com/?path=/story/components-timeline--without-toggle
=> feat: add prop to show/hide toggle in timeline item

styleguide/src/Indicators/Alert/Alert.tsx
Adicionando prop `customIcon` para o componente de alert.
Necessidade de usar um ícone personalizado para uma alert. Ex: 
https://www.figma.com/file/Z2WDD4SH8zwaJC2K5wbtMO/Sistema-Integrado?node-id=3%3A3743
Alterando a propriedade `customIcon`, o ícone da alert deve mudar de acordo com o selecionado.
https://60d36f60766f7d0045e93767-hqbgvntwlq.chromatic.com/?path=/story/indicators-alert--default&args=type:danger;customIcon:exclamationCircle
=> feat: add prop custom icon to alert

styleguide/src/Components/Button/Button.spec.tsx, styleguide/src/Components/Button/Button.tsx, styleguide/src/Forms/Input/Input.spec.tsx, styleguide/src/Forms/commonStyles.ts
Ajusta tamanho da fonte e altura do botão `small`.
Botão `small` estava menor do que o [previsto no design system](https://www.figma.com/file/Z2WDD4SH8zwaJC2K5wbtMO/Sistema-Integrado?node-id=95%3A7094).
https://60d36f60766f7d0045e93767-bjxjswsrso.chromatic.com/?path=/story/components-button--small
antes:
depois:
=> fix: button small size

styleguide/src/Indicators/InformationBox/InformationBox.spec.tsx, styleguide/src/Indicators/InformationBox/InformationBox.tsx, tailwindcss/src/defaultPreset.js
Adds the new 'info' variant to informationBox component and it's corresponding color palette
The lack of both variant and color palette
=> adds new focus colors and info variant

styleguide/src/Components/SidebarFixed/SidebarFixed.tsx
Não era possível adicionar um título no cabeçalho alinhado com os botões de ação.
Manter o mesmo comportamento/posição dos elementos quando não houver título. Quando tiver, o título deverá ficar alinhado à esquerda e os botões de ação à direita.
=> Add title property to SidebarFixed

styleguide/src/Components/Button/Button.tsx
Fix button style when variant is onlyText;
Glued classes, ex: `border-0text-f6`
=> fix: onlyText classes

tailwindcss/src/_variables.scss
Atualizando cor `focus-dark` de acordo com o "Sistema Integrado":
Cor atual:
=> fix: adjust color focus dark

styleguide/src/Indicators/InformationBox/InformationBox.spec.tsx, styleguide/src/Indicators/InformationBox/InformationBox.tsx, styleguide/src/Indicators/InformationBox/InformationBoxt.stories.tsx, tailwindcss/src/_variables.scss
Deprecando tipo `tip` do componente `InformationBox` e adicionando `success` - conforme [Design System](https://www.figma.com/file/Z2WDD4SH8zwaJC2K5wbtMO/Sistema-Integrado?type=design&node-id=2391-20860&mode=design&t=osPE855AzaG0iLyg-4).
Obs: Pelo que pesquisei o `tip` só foi [usado em projetos antigos](https://github.com/search?q=org%3Alojaintegrada%20%22%3CInformationBox%22&type=code), não mais no ar.
Ajustando ícones, cores do título e fundo do `InformationBox`;
=> fix: adjust InformationBox

styleguide/src/Navigation/Stepper/Stepper.spec.tsx, styleguide/src/Navigation/Stepper/Stepper.stories.tsx, styleguide/src/Navigation/Stepper/index.tsx
Implementa o componente de Stepper
=> Stepper component

styleguide/src/Indicators/Status/Status.spec.tsx, styleguide/src/Indicators/Status/Status.tsx
Além do suporte a nova cor de fundo (bg-success-dark), foi permitido enviar um elemento na propriedade 'description'.
=> Add variant in Status component

styleguide/src/Forms/Toggle/Toggle.tsx, styleguide/src/Indicators/Badge/Badge.spec.tsx, styleguide/src/Indicators/Badge/Badge.tsx, styleguide/src/Indicators/InformationBox/InformationBox.spec.tsx, styleguide/src/Indicators/InformationBox/InformationBox.tsx
Badge: Suporte a nova cor de fundo (bg-primary-light).
InformationBox: Cor do título da variante 'warning' alterada (text-warning-bold).
Toggle: Permitido enviar um elemento na propriedade 'label'.
=> Add variant in Badge component

styleguide/src/Components/Tabs/Tabs.spec.tsx, styleguide/src/Components/Tabs/Tabs.stories.tsx, styleguide/src/Components/Tabs/TabsItem.interface.ts, styleguide/src/Components/Tabs/TabsItem.tsx
Novo atributo `titleComplement` suportado na lista de itens, necessário para casos onde deve-se ter um elemento ao lado do texto.
=> Add complement to Tabs component
